version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    depends_on:
      - db
    ports:
      - "4001:3000"
    volumes:
      - .:/myapp
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/myapp/node_modules
    env_file: .env
    environment:
      RAILS_ENV: development
      BUNDLE_PATH: /usr/local/bundle/gems
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
volumes:
  gem_cache:
  db_data:
  node_modules:
